### ISSUE TITLE
Find best way to validate policy rules

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-sdk-validation#41] opened 2018-06-29 09:36 UTC
As commented by @felipevicens, the validator could also validate policy rule descriptor (in drl format) in order to make sure that the generated rules are valid. Here an [example of policies](https://github.com/sonata-nfv/tng-policy-mngr/blob/master/rules/gsge68aeee88a704249ab2dc03eda6b3e8b/gsge68aeee88a704249ab2dc03eda6b3e8b.drl)

Not a priority at this point, just created to keep track of this.

**Comment by anapolg** [comment] 2019-05-08 10:54
Duplicate of #120

**Closed by anapolg** 2019-05-08 10:54 UTC
Labels: question
